### PR TITLE
Add snapshot support

### LINKED ISSUE #15: Add SnapshotID please ;-)
Hello,

I don't know GO otherwise I'd attempt to add this request. Simply, Vultr allows for loading a pre-stored snapshot, hostname and label onto the new host. I'd like these to be added in as it is a very handy feature.

In summary, please add;

1. snapshotid
2. hostname
3. label
4. there are many others available here: https://www.vultr.com/api/#server_create

Example: 
curl -H 'API-Key: EXAMPLE' https://api.vultr.com/v1/server/create --data 'DCID=1' --data 'VPSPLANID=1' --data 'OSID=127' --data 'SNAPSHOTID=123456asdf456' --data 'hostname=domain.com' --data 'label=domain.com'.

If you can provide some simple guidance to add then I can do so ;-)

### PR DESCRIPTION
**Pull request by twang2218**
Fixes #15 

Signed-off-by: Tao Wang <twang2218@gmail.com>

### CODE REVIEW

**Comment by twang2218** [comment]
ping @janeczku

**Comment by janeczku** [comment]
@twang2218 I think we should automatically set `OSID 164` when the `vultr-snapshot-id` is specified?

**Comment by twang2218** [comment]
Yes, the OSID should be `164` in case `vultr-snapshot-id` is specified. I update the commit to assign the OSID to `164` if it's `159` (defaultOS), so user still be able to assign another OSID, in case if there is a future changes in the API, and the driver code haven't been updated yet.

**Comment by janeczku** [comment]
Thanks so much @twang2218!

**Pull request merged**
