### PR TITLE
Making API endpoint a configurable machine parameter

### PR DESCRIPTION
**Pull request by bfosberry**

### CODE REVIEW

**Comment by gsmaul** [comment]
Vultr developer here. I can confirm that bfosberry's patch is quite useful. We add API endpoints from time to time, and this patch will allow systems using this driver (like Rancher) to take advantage of them.

**Comment by janeczku** [comment]
Thanks @bfosberry 
I am curious though, are there any endpoints other then `https://api.vultr.com/` ?

**Comment by gsmaul** [comment]
None publicly, but we have several for testing and special client needs.

**Comment by bfosberry** [comment]
Thanks!

**Pull request merged**
